[build.env]
passthrough = ["RUSTFLAGS"]

[target.mipsel-unknown-linux-musl]
build-std = true

[target.mips-unknown-linux-musl]
build-std = true

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:edge"
