#!/usr/bin/env bash
# Ask the advisory database about the vendored crates.
#
# Why this exists: `cargo deny check advisories` reads `Cargo.lock`, and a
# vendored crate arrives through `[patch.crates-io] { path = … }` — a package
# with no `source`. The advisory check skips those, so `vendor/rustls` sat at
# 0.23.43 while RUSTSEC-2026-0285 (patched: >= 0.23.45) was published, and the
# job reported "advisories ok". This builds a throwaway manifest that names each
# vendored crate at the *published* version of the source it carries, resolves a
# lock for it, and runs the same check against that.
#
# Auxiliary tooling: it writes only under `target/`, and cargo never invokes it.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/target/vendor-advisories"
rm -rf "$out"
mkdir -p "$out"

{
    echo '[package]'
    echo 'name = "vendor-advisories"'
    echo 'version = "0.0.0"'
    echo 'edition = "2021"'
    echo 'publish = false'
    echo
    # Its own workspace root: without this, cargo walks up into the repository's
    # and refuses the manifest as a member that is not listed.
    echo '[workspace]'
    echo
    echo '[dependencies]'
    for dir in "$root"/vendor/*/; do
        name=$(sed -n 's/^name = "\(.*\)"/\1/p' "$dir/Cargo.toml" | head -1)
        version=$(sed -n 's/^version = "\(.*\)"/\1/p' "$dir/Cargo.toml" | head -1)
        if [ -z "$name" ] || [ -z "$version" ]; then
            echo "::error::$(basename "$dir") has no name/version in its Cargo.toml" >&2
            exit 1
        fi
        # `rustls-rustcrypto` is the one vendored crate that is a *workspace
        # member*, so the step above already reads its real dependency graph —
        # and it is also the one whose patch changes those dependencies (our copy
        # drops `webpki`; the published 0.0.2-alpha still pulls the vulnerable
        # `rustls-webpki 0.102.8`, RUSTSEC-2026-0104). Asking about the published
        # version here would report a defect this tree does not have.
        if [ "$name" = "rustls-rustcrypto" ]; then
            printf '   %s %s (workspace member: checked by cargo deny above)\n' "$name" "$version" >&2
            continue
        fi
        printf '%s = "=%s"\n' "$name" "$version"
        printf '   %s %s\n' "$name" "$version" >&2
    done
} > "$out/Cargo.toml"

# Its own advisory config: the repository's `deny.toml` carries `ignore` entries
# for advisories this tree does not contain (the RSA timing one, `paste` inside
# the provider), and cargo-deny warns about every ignore it never meets.
cat > "$out/deny.toml" <<'EOF'
# Generated by scripts/vendor-advisories.sh — see it for why this is not the
# repository's deny.toml.
[advisories]
version = 2
EOF

# The generated crate needs a target, or cargo refuses the manifest outright.
mkdir -p "$out/src"
: > "$out/src/lib.rs"

cd "$out"
# `cargo` is on PATH in CI and in a login shell; a bare `bash script.sh` on
# Windows may have a PATH without the rustup shim, so fall back to `$CARGO_HOME`.
cargo_bin=$(command -v cargo || true)
if [ -z "$cargo_bin" ]; then
    cargo_home="${CARGO_HOME:-${HOME:-${USERPROFILE:-}}/.cargo}"
    for candidate in "$cargo_home/bin/cargo" "$cargo_home/bin/cargo.exe"; do
        [ -x "$candidate" ] && cargo_bin="$candidate" && break
    done
fi
if [ -z "$cargo_bin" ]; then
    echo "::error::cargo not found: put it on PATH or set CARGO_HOME" >&2
    exit 1
fi

# `cargo deny` is the separate `cargo-deny` binary, and cargo finds it on PATH —
# which a bare `bash script.sh` may not carry (and on WSL the Windows form and
# the `/mnt/…` form resolve `.exe` differently, so rewriting PATH is the wrong
# move). Resolve the subcommand itself, next to the cargo that was found.
deny_bin=$(command -v cargo-deny || command -v cargo-deny.exe || true)
if [ -z "$deny_bin" ]; then
    for candidate in "$(dirname "$cargo_bin")/cargo-deny" "$(dirname "$cargo_bin")/cargo-deny.exe"; do
        [ -x "$candidate" ] && deny_bin="$candidate" && break
    done
fi
if [ -z "$deny_bin" ]; then
    echo "::error::cargo-deny not found: install it (cargo install --locked --version 0.20.2 cargo-deny)" >&2
    exit 1
fi

# A vendored crate whose published version no longer exists (a yanked release, a
# version that was never published) is not an advisory question, but it must not
# pass silently either: say what failed and let a human decide.
if ! "$cargo_bin" generate-lockfile --quiet; then
    echo "::error::could not resolve the vendored crates against crates.io; see above" >&2
    exit 1
fi

"$deny_bin" deny --locked --config "$out/deny.toml" check advisories
